"""Delete license key from tv_details

Revision ID: 9c0265397c7f
Revises: 9c99206fccb2
Create Date: 2025-02-14 22:47:31.544719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0265397c7f'
down_revision: Union[str, None] = '9c99206fccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_details', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tv_details', 'stores', ['store_id'], ['id'])
    op.drop_column('tv_details', 'license_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_details', sa.Column('license_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tv_details', type_='foreignkey')
    op.drop_column('tv_details', 'store_id')
    # ### end Alembic commands ###
