"""Create static info table

Revision ID: e596e70b7ba9
Revises: 9c0265397c7f
Create Date: 2025-02-19 21:47:22.432947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e596e70b7ba9'
down_revision: Union[str, None] = '9c0265397c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dns_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('static_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('mask', sa.String(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stores', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stores', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'region_id')
    op.drop_table('static_info')
    op.drop_table('dns_table')
    op.drop_table('regions')
    # ### end Alembic commands ###
